# 1. 추천시스템을 위한 노래 가사 정리

### 긴 노래 가사를 전처리 과정 없이 바로 코사인-유사도 사용해서 추천 시스템 구현하면 정확도가 떨어져, 노래 가사 형태소 분석 후 명사/동사/형용사를 이용하여 추천 시스템 구현

In [71]:
lyric = pd.read_csv('lyricdata/lyric_label(2개로)_new2.csv')
# lyric = lyric.drop(columns=['Unnamed: 0', '_id'])
lyric

,genre,title,singer,lyric,lyric_clean,label
0,NaN,NaN,NaN,text,NaN,NaN
1,발라드,사랑하는 그대여,신용재 (2F),사랑하는 그대 오늘 하루도 참 고생했어요 많이 힘든 그대 힘이든 그댈 안아주고 싶어...,사랑 하는 그대 오늘 하루 참 고생 했어요 힘든 그대 힘 그 댈 안아주고 싶어요 지...,1.0
2,발라드,좋아요,방탄소년단,너와의 니가 올리는 모든 사진마다 좋아...,너 니 올리는 모든 사진 좋아요 남발 하는 처음 보는 저 남자 누구 맞다 나 이제 ...,0.0
3,댄스,Darling,걸스데이,요즘 연인들은 하고 시작한대 사랑을 어리숙하고 난 낯을 가리는데 사람을 내 ...,요즘 연인 하고 사랑 어리숙하고 난 낯 가리는데 사람 내 틀 안 갇혀 매일 가짜 같...,1.0
4,댄스,맙소사,"황태지 (황광희, 태양, 지드래곤)",맙소사 맙소사 ...,태어날 때 가 우린 신 날 땐 아무 날 심판 하지 해 절대 양 옆 앞 뒤 줄 맞춰 ...,1.0
...,...,...,...,...,...,...
3848,댄스,Dear Santa,소녀시대-태티서 (Girls' Generation-TTS),내 얘길 들어줘요 나 간절하게 원하고 있죠 그의 맘도 같기를 ...,내 얘길 들어줘요 나 간절하게 원하고 있죠 그 맘 같기를 설레였던 너 나 젠 조금 ...,1.0
3849,랩/힙합,오만과 편견 (Feat. 수란),지코 (ZICO),난 매사에 철저하고 냉소적이니까 여자에게 정 주는 건 소모적인 짓이야 도둑처럼 연애...,난 매사 철저하고 냉소 여자 정 주는 건 소모 짓 도둑 연애 하는 저 처지 봐 다치...,0.0
3850,록/메탈,천년의 사랑,박완규,이대로 널 보낼 수는 없다고 밤을 세워 간절히 기도했지만 더 이상 널 사랑할 수 없...,널 보낼 수 없다고 밤 세워 간절히 기도 했지만 더 이상 널 사랑 할 수 없다면 차...,0.0
3851,록/메탈,For You,플라워,그대 만나 시작됐던 내 간절한 사랑이 영원토록 계속되길 원해 그대보다 단 하루만 더...,그대 만나 시작 됐던 내 간절한 사랑 영원 계속 되길 원해 그대 단 하루 더 살 해...,1.0
3852,댄스,너랑 나,아이유,시곌 보며 속삭이는 비밀들 간절한 내 맘속 이야기 지금 내 모습을 해쳐도 좋아 나를...,시곌 보며 속삭이는 비밀 간절한 내 맘속 이야기 지금 내 모습 해쳐도 좋아 나를 재...,1.0

In [72]:
def lyric_processing(sent):
    words = okt.pos(sent)
    words = [w for w in words if ('Adjective' in w or 'Verb' in w or 'Noun' in w)]
    t = []
    for i in words:
        t.append(i[0])
    result = ' '.join(t)
    
    return result

In [73]:
lyric = pd.read_csv('lyricdata/lyric_label_final.csv')
lyric

,genre,title,singer,lyric,label,lyric_clean
0,"인디음악, 포크/블루스",우리는 우리 나름의 사랑을,변민석,우리는 우리 나름의 사랑을 하나둘 세워가고 그대의 진한 마음을 알아서 눈가를 내줍니...,0,우리 우리 나름 사랑 하나 둘 세워가고 그대 진한 마음 알아서 눈가 내줍니다 밤비 ...
1,랩/힙합,가면을 쓴 달,류현준,가면에 가린 달 가면에 가린 밤 가면에 가린 날 가면에 가면에 숨어버린 나를 찾지 ...,0,가면 가린 달 가면 가린 밤 가면 가린 날 가면 가면 숨어 버린 나를 찾지 않았으면...
2,"인디음악, 포크/블루스",옥탑방 고양이,김바람,내겐 한 가지 간절한 바람이 있어 수만 가지 말들엔 다 이유가 있어 그 말들의 가치...,1,내겐 한 가지 간절한 바람 있어 수만 가지 말 이유 있어 그 말 가치 알기에 하길 ...
3,댄스,불시착 (STAY YOUNG),AB6IX (에이비식스),무슨 말을 해도 소용없잖아요 내 속이 어떤지도 모르잖아요 간절하게 딛고 있는 발걸음...,0,무슨 말 해도 소용없잖아요 내 속이 지도 모르잖아요 간절하게 딛고 있는 발걸음 당신...
4,록/메탈,붕어빵 Freedom (Prod. EVEN),"이븐, 김켄타, 한수정",날 적시는 차가운 겨울 밤공기와 파도치는 별빛에 녹아든 고소한 향 눈 덮힌 거리 위...,0,날 적시는 차가운 겨울 밤 공기 파도치는 별빛 녹아든 고소한 향 눈 덮힌 거리 위 ...
...,...,...,...,...,...,...
8626,발라드,U R,태연 (TAEYEON),오랫동안 내 마음엔 구름 가득 비가 내려 따스한 햇살 비추길 간절히 바랬죠 어깨를 ...,1,내 마음 구름 가득 비 내려 따스한 햇살 비추길 간절히 바랬 어깨 적신 빗방울 마르...
8627,"인디음악, 포크/블루스",사랑한다고 말했잖아,어쿠스틱 콜라보,그냥 견뎌질 거란 그 한 마디 말에 우리 그 간절했던 순간들 잊혀지기엔 너무 소중해...,0,그냥 견뎌질 거란 그 한 마디 말 우리 그 간절했던 순간 잊혀지 기 소중해 숨 멎을...
8628,랩/힙합,오만과 편견 (Feat. 수란),지코 (ZICO),난 매사에 철저하고 냉소적이니까 여자에게 정 주는 건 소모적인 짓이야 도둑처럼 연애...,0,난 매사 철저하고 냉소 여자 정 주는 건 소모 짓 도둑 연애 하는 저 처지 봐 다치...
8629,록/메탈,천년의 사랑,박완규,이대로 널 보낼 수는 없다고 밤을 세워 간절히 기도했지만 더 이상 널 사랑할 수 없...,0,널 보낼 수 없다고 밤 세워 간절히 기도 했지만 더 이상 널 사랑 할 수 없다면 차...
8630,댄스,너랑 나,아이유,시곌 보며 속삭이는 비밀들 간절한 내 맘속 이야기 지금 내 모습을 해쳐도 좋아 나를...,1,시곌 보며 속삭이는 비밀 간절한 내 맘속 이야기 지금 내 모습 해쳐도 좋아 나를 재...

In [74]:
lyric = lyric.drop_duplicates(['title'])
lyric

,genre,title,singer,lyric,label,lyric_clean
0,"인디음악, 포크/블루스",우리는 우리 나름의 사랑을,변민석,우리는 우리 나름의 사랑을 하나둘 세워가고 그대의 진한 마음을 알아서 눈가를 내줍니...,0,우리 우리 나름 사랑 하나 둘 세워가고 그대 진한 마음 알아서 눈가 내줍니다 밤비 ...
1,랩/힙합,가면을 쓴 달,류현준,가면에 가린 달 가면에 가린 밤 가면에 가린 날 가면에 가면에 숨어버린 나를 찾지 ...,0,가면 가린 달 가면 가린 밤 가면 가린 날 가면 가면 숨어 버린 나를 찾지 않았으면...
2,"인디음악, 포크/블루스",옥탑방 고양이,김바람,내겐 한 가지 간절한 바람이 있어 수만 가지 말들엔 다 이유가 있어 그 말들의 가치...,1,내겐 한 가지 간절한 바람 있어 수만 가지 말 이유 있어 그 말 가치 알기에 하길 ...
3,댄스,불시착 (STAY YOUNG),AB6IX (에이비식스),무슨 말을 해도 소용없잖아요 내 속이 어떤지도 모르잖아요 간절하게 딛고 있는 발걸음...,0,무슨 말 해도 소용없잖아요 내 속이 지도 모르잖아요 간절하게 딛고 있는 발걸음 당신...
4,록/메탈,붕어빵 Freedom (Prod. EVEN),"이븐, 김켄타, 한수정",날 적시는 차가운 겨울 밤공기와 파도치는 별빛에 녹아든 고소한 향 눈 덮힌 거리 위...,0,날 적시는 차가운 겨울 밤 공기 파도치는 별빛 녹아든 고소한 향 눈 덮힌 거리 위 ...
...,...,...,...,...,...,...
8626,발라드,U R,태연 (TAEYEON),오랫동안 내 마음엔 구름 가득 비가 내려 따스한 햇살 비추길 간절히 바랬죠 어깨를 ...,1,내 마음 구름 가득 비 내려 따스한 햇살 비추길 간절히 바랬 어깨 적신 빗방울 마르...
8627,"인디음악, 포크/블루스",사랑한다고 말했잖아,어쿠스틱 콜라보,그냥 견뎌질 거란 그 한 마디 말에 우리 그 간절했던 순간들 잊혀지기엔 너무 소중해...,0,그냥 견뎌질 거란 그 한 마디 말 우리 그 간절했던 순간 잊혀지 기 소중해 숨 멎을...
8628,랩/힙합,오만과 편견 (Feat. 수란),지코 (ZICO),난 매사에 철저하고 냉소적이니까 여자에게 정 주는 건 소모적인 짓이야 도둑처럼 연애...,0,난 매사 철저하고 냉소 여자 정 주는 건 소모 짓 도둑 연애 하는 저 처지 봐 다치...
8629,록/메탈,천년의 사랑,박완규,이대로 널 보낼 수는 없다고 밤을 세워 간절히 기도했지만 더 이상 널 사랑할 수 없...,0,널 보낼 수 없다고 밤 세워 간절히 기도 했지만 더 이상 널 사랑 할 수 없다면 차...
8630,댄스,너랑 나,아이유,시곌 보며 속삭이는 비밀들 간절한 내 맘속 이야기 지금 내 모습을 해쳐도 좋아 나를...,1,시곌 보며 속삭이는 비밀 간절한 내 맘속 이야기 지금 내 모습 해쳐도 좋아 나를 재...

In [75]:
lyric.to_csv('lyricdata/lyric_label_final.csv', index = False)

In [76]:
len(lyric)

8631

# 2. 노래 추천

## 1) 일치하는 감정의 노래 추천

In [77]:
import itertools
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel


def okt_tokenize(sent):
    words = okt.pos(sent)
    words = [w for w in words if ('Adjective' in w or 'Verb' in w or 'Noun' in w)]
    return words

def func(sentence):
    result = okt_tokenize(sentence)
    t = []
    for j in range(len(result)):
        t.append(str(result[j][0]))
    return t

def recommend(sentence):
    new_sentence = sentence_preprocessing(sentence)
    encoded = tokenizer.texts_to_sequences([new_sentence]) # 정수 인코딩
    pad_new = pad_sequences(encoded, maxlen = max_len) # 패딩
    score = loaded_model.predict(pad_new) # 예측
    if score.argmax() == 0:
        df_rec = lyric[lyric['label'] == 1]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 1:
        df_rec = lyric[lyric['label'] == 0]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 2:
        df_rec = lyric[lyric['label'] == 0]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 3:
        df_rec = lyric[lyric['label'] == 0]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 4:
        df_rec = lyric[lyric['label'] == 0]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 5:
        df_rec = lyric[lyric['label'] == 0]
        df_rec = df_rec.reset_index(drop=True)
        
    df_rec.loc[len(df_rec)] = ['', '', '', sentence, '','']
    c = func(df_rec['lyric'][len(df_rec)-1])
    df_rec['lyric_clean'][len(df_rec)-1] = ' '.join(c)
    
    tfidf = TfidfVectorizer()
    tfidf_matrix = tfidf.fit_transform(df_rec['lyric_clean'])
    
    cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
    
    indices = pd.Series(df_rec.index, index=df_rec['title']).drop_duplicates()
    
    
    idx = indices['']
    
    sim_scores = list(enumerate(cosine_sim[idx]))
    
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    sim_scores = sim_scores[1:6]
    
    
    song_indices = [i[0] for i in sim_scores]
    
    
    return df_rec.iloc[song_indices,1:3]

## 2) 반대 감정의 노래 추천

In [78]:
# 반대 감정의 노래 추천
def recommend2(sentence):
    new_sentence = sentence_preprocessing(sentence)
    encoded = tokenizer.texts_to_sequences([new_sentence]) # 정수 인코딩
    pad_new = pad_sequences(encoded, maxlen = max_len) # 패딩
    score = loaded_model.predict(pad_new) # 예측
    if score.argmax() == 0:
        df_rec = lyric[lyric['label'] == 0]
        df_rec = df_rec.reset_index(drop=True)
        print('행복해보여요! 이 노래는 어때요?')
    if score.argmax() == 1:
        print('화나보여요. 이 노래는 어때요?')
        df_rec = lyric[lyric['label'] == 1]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 2:
        print('우울해보여요. 이 노래는 어때요?')
        df_rec = lyric[lyric['label'] == 1]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 3:
        print('불안해보여요. 이 노래는 어때요?')
        df_rec = lyric[lyric['label'] == 1]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 4:
        print('놀라셨나요? 이 노래는 어때요?')
        df_rec = lyric[lyric['label'] == 1]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 5:
        print('지루해보여요. 이 노래는 어때요?')
        df_rec = lyric[lyric['label'] == 1]
        df_rec = df_rec.reset_index(drop=True)
        
    df_rec.loc[len(df_rec)] = ['', '', '', sentence, '','']
    c = func(df_rec['lyric'][len(df_rec)-1])
    df_rec['lyric_clean'][len(df_rec)-1] = ' '.join(c)
    
    tfidf = TfidfVectorizer()
    tfidf_matrix = tfidf.fit_transform(df_rec['lyric_clean'])
    
    cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
    
    indices = pd.Series(df_rec.index, index=df_rec['title']).drop_duplicates()
    
    
    idx = indices['']
    
    sim_scores = list(enumerate(cosine_sim[idx]))
    
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    sim_scores = sim_scores[1:6]
    
    
    song_indices = [i[0] for i in sim_scores]
    
    
    return df_rec.iloc[song_indices,1:3]

In [79]:
t='오늘 너무 우울하다.. 집에서 하루 종일 뒹굴거렸더니 너무 우울하다. 내일은 집 앞에 산책이라도 다녀와야겠다.'
recommend(t)

                          title     singer
3163  우울시계 (Feat. 종현 Of SHINee)        아이유
721                    With you       Uken
1905                    잃어버린 오늘        심재준
3031                     내일 할 일   윤종신, 성시경
4168             첫째 날 (With 나얼)  Ecobridge

In [80]:
recommend2(t)

우울해보여요. 이 노래는 어때요?

              title                                             singer
706      Be Happier                                 바이더문 (BY THE MOON)
464        PLAYLIST  김동현 (AB6IX), 이대휘 (AB6IX), 홍성준 (BDC), 윤정환 (BDC)...
2257            너너너                                                이소예
1054  화내도 하루 웃어도 하루                              Hertz Charley (헤르츠찰리)
201        너와 나의 내일                                      2F (신용재, 김원주)

In [81]:
t='나도 네게 이름 몇 자로 설레는 존재면 좋겠다'
recommend(t)

                   title       singer
3856            잘됐으면 좋겠다          홍대광
673              이름 없는 나       KOLAVO
3326     10분이 늦어 이별하는 세상      좋아서하는밴드
3442            너의 존재 위에  심규선 (Lucia)
1668  All Wet (feat. 밤샘)         Wasp

In [82]:
recommend2(t)

행복해보여요! 이 노래는 어때요?

                               title            singer
3171  남자친구가 생겼으면 좋겠다 (Feat. 소심한 오빠들)                쇼코
3170       여자친구가 생겼으면 좋겠다 (Feat. 쇼코)           소심한 오빠들
562       Summer Night (feat. HAROO)              포플레이
2582    ONE TIME (FEAT. CHERRY COKE)  Deepshower (딥샤워)
1185                        이 계절이 오면               김혜서

In [83]:
t='오늘 한게 아무것도 없다. 나는 왜 이렇게 사는 걸까. 삶의 의미가 없다'
recommend(t)

                             title                                 singer
1694                            사계                                     부경
1116                          모래시계                                    지성환
3168                       10월의 날씨                                   10CM
1695  사라진 모든 것들에게(with ELLE KOREA)  코드 쿤스트 (CODE KUNST), 잔나비 최정훈, 사이먼 도미닉
1387               뿌옇다 (Feat. 이성연)                               코끼리 숨바꼭질

# 3. 영화 추천

### 영화 장르별 임의로 감정을 나눠준 후, 분석한 일기의 감정과 일치하는 감정의 영화 추천

In [84]:
movie = pd.read_excel('data/영화 7장르 분류.xlsx')
movie.drop(columns=['Unnamed: 0'],inplace=True)
movie

               제목  국적   장르               감독
0       신과함께-죄와 벌  한국  판타지              김용화
1       신과함께-인과 연  한국  판타지              김용화
2           택시운전사  한국  드라마               장훈
3    어벤져스: 인피니티 워  미국   액션      안소니 루소,조 루소
4        보헤미안 랩소디  미국  드라마          브라이언 싱어
..            ...  ..  ...              ...
334    찰리와 초콜릿 공장  미국  판타지             팀 버튼
335       오즈의 마법사  미국  판타지           빅터 플레밍
336        미녀와 야수  미국  판타지             빌 콘던
337  센과 치히로의 행방불명  일본  판타지         미야자키 하야오
338      드래곤 길들이기  미국  판타지  딘 드블루아, 크리스 샌더스

[339 rows x 4 columns]

In [85]:
movie['장르'].unique()

array(['판타지', '드라마', '액션', '코미디', '멜로/로맨스', '스릴러', '어드벤처'], dtype=object)

In [86]:
movie[movie['장르'] == '어드벤처']

                    제목  국적    장르               감독
36              슈퍼배드 3  미국  어드벤처     피에르 꼬팽,카일 발다
41             인크레더블 2  미국  어드벤처           브래드 버드
55     조선명탐정: 흡혈괴마의 비밀  한국  어드벤처              김석윤
59                 모아나  미국  어드벤처     론 클레멘츠,존 머스커
67         혹성탈출: 종의 전쟁  미국  어드벤처            맷 리브스
73         쥬만지: 새로운 세계  미국  어드벤처          제이크 캐스단
74          콩: 스컬 아일랜드  미국  어드벤처        조던 복트-로버츠
116          마당을 나온 암탉  한국  어드벤처          오성윤,민성아
152               미니언즈  미국  어드벤처     피에르 꼬팽,카일 발다
157             쥬라기 월드  미국  어드벤처         콜린 트레보로우
159            도리를 찾아서  미국  어드벤처          앤드류 스탠튼
160                트로이  미국  어드벤처          볼프강 페터젠
169                 킹콩  미국  어드벤처            피터 잭슨
174              쿵푸팬더3  미국  어드벤처    여인영,알레산드로 칼로니
183     미션 임파서블: 로그네이션  미국  어드벤처        크리스토퍼 맥쿼리
186               주토피아  미국  어드벤처    바이론 하워드,리치 무어
200                정글북  미국  어드벤처            존 파브로
205   레버넌트: 죽음에서 돌아온 자  미국  어드벤처  알레한드로 곤잘레스 이냐리투
224             쿵푸팬더 2  미국  어드벤처              여인영
229              쿵푸 팬더  미국  어드벤처    마크 오스본,존 스티븐슨
230       해적: 바다로 간 산적  한국  어드벤처              이석훈
232  좋은 놈, 나쁜 놈, 이상한 놈  한국  어드벤처              김지운
239         드래곤 길들이기 2  미국  어드벤처          딘 데블로이스
240           벼랑 위의 포뇨  일본  어드벤처         미야자키 하야오
255                백두산  한국  어드벤처          이해준,김병서
261              라이온 킹  미국  어드벤처            존 파브로
287  주먹왕 랄프 2: 인터넷 속으로  미국  어드벤처            리치 무어
295         드래곤 길들이기 3  미국  어드벤처          딘 데블로이스
300           드래곤 길들이기  미국  어드벤처          딘 데블로이스
302               겨울왕국  미국  어드벤처      크리스 벅,제니퍼 리
306                타이탄  미국  어드벤처         루이스 리테리어

In [87]:
def movie_recommend(sentence):
    new_sentence = sentence_preprocessing(sentence)
    encoded = tokenizer.texts_to_sequences([new_sentence]) # 정수 인코딩
    pad_new = pad_sequences(encoded, maxlen = max_len) # 패딩
    score = loaded_model.predict(pad_new) # 예측
    if score.argmax() == 0:
        df_rec = movie[(movie['장르'] == '멜로/로맨스') | (movie['장르'] == '드라마')]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 1:
        df_rec = movie[movie['장르'] == '드라마']
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 2:
        df_rec = movie[movie['장르'] == '코미디']
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 3:
        df_rec = movie[(movie['장르'] == '어드벤처') | (movie['장르'] == '코미디')]
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 4:
        df_rec = movie[movie['장르'] == '판타지']
        df_rec = df_rec.reset_index(drop=True)
    if score.argmax() == 5:
        df_rec = movie[(movie['장르'] == '액션') | (movie['장르'] == '스릴러')]
        df_rec = df_rec.reset_index(drop=True)
        
    recommend_movie = df_rec.sample(5)
    
    return recommend_movie

In [88]:
movie.sample(5)

           제목  국적      장르        감독
28       암수살인  한국     드라마       김태균
86    어거스트 러쉬  미국     드라마   커스틴 쉐리단
169        킹콩  미국    어드벤처     피터 잭슨
240  벼랑 위의 포뇨  일본    어드벤처  미야자키 하야오
318      타이타닉  미국  멜로/로맨스   제임스 카메론